const fs = require('fs');
const filePath = 'c:/Users/digesh prajapati/Desktop/salvinindia/src/pages/TurnkeyProject/components/IndustrialFlourMillingDetailPage.jsx';
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/Complete Potato Powder Dehydration Plant/g, 'Complete Industrial Flour Milling Plant');
content = content.replace(/Potato Powder Dehydration Plant/g, 'Industrial Flour Milling Plant');
content = content.replace(/Potato Powder <span className="ifm-accent">Workflow<\/span>/g, 'Industrial Flour Milling <span className="ifm-accent">Workflow<\/span>');
content = content.replace(/Advanced turnkey solution for potato washing, peeling, slicing, dehydration, pulverizing, sieving, and packaging to produce premium quality potato powder for the food industry\./g, 'Our Industrial Flour Milling Plant is engineered for efficient wheat processing and premium flour production. The plant integrates cleaning, conditioning, roller milling, plansifting, grading and automatic packaging systems to deliver consistent flour quality with high extraction rates.');
content = content.replace(/Advanced turnkey solution for potato washing, peeling, slicing, dehydration, pulverizing, sieving, and packaging to produce premium quality potato powder\./g, 'Advanced turnkey solution for industrial flour milling.');
content = content.replace(/Our plants convert raw potatoes into premium potato powder using highly efficient dehydration, milling, and sieving processes\. This ensures a final product with excellent rehydration properties, long shelf life, and consistent mesh size\./g, 'Our Industrial Flour Milling Plant is engineered for efficient wheat processing and premium flour production. The plant integrates cleaning, conditioning, roller milling, plansifting, grading and automatic packaging systems to deliver consistent flour quality with high extraction rates.');
content = content.replace(/<p className="ifm-overview__feature-title">High Yield<\/p>[\s\S]*?<p className="ifm-overview__feature-desc">Maximum potato powder recovery per batch<\/p>/g, '<p className="ifm-overview__feature-title">Premium Flour Production</p>\\n                    <p className="ifm-overview__feature-desc">High-quality Atta, Maida, Sooji and Rava output.</p>');
content = content.replace(/<p className="ifm-overview__feature-title">Hygienic Process<\/p>[\s\S]*?<p className="ifm-overview__feature-desc">Food grade SS304\\/SS316L construction<\/p>/g, '<p className="ifm-overview__feature-title">Fully Automated Processing Line</p>\\n                    <p className="ifm-overview__feature-desc">Reduced labor and increased efficiency.</p>');
content = content.replace(/<p className="ifm-overview__feature-title">Consistent Quality<\/p>[\s\S]*?<p className="ifm-overview__feature-desc">Uniform mesh size and moisture control<\/p>/g, '<p className="ifm-overview__feature-title">Advanced Milling Technology</p>\\n                    <p className="ifm-overview__feature-desc">Maximum flour yield and product consistency.</p>');
content = content.replace(/<p className="ifm-overview__feature-title">Energy Efficient<\/p>[\s\S]*?<p className="ifm-overview__feature-desc">Optimized drying and pulverizing systems<\/p>/g, '<p className="ifm-overview__feature-title">Complete Turnkey Solution</p>\\n                    <p className="ifm-overview__feature-desc">Design, manufacturing and installation support.</p>');
content = content.replace(/\/turnkey-brochures\/images\/potato-powder-dehydration-gallery\/1_washing_destoning\.jpg/g, '/turnkey-brochures/images/flour-milling-gallery/6_automatic_flour_packaging.jpg');
content = content.replace(/\/turnkey-brochures\/images\/potato-powder-dehydration-gallery\/6_packaging_machine\.jpg/g, '/turnkey-brochures/images/flour-milling-gallery/6_automatic_flour_packaging.jpg');
content = content.replace(/From raw potato washing to fine powder packaging, our continuous processing line guarantees efficiency and quality at every step\./g, 'From raw wheat cleaning to premium flour packaging, our continuous processing line guarantees efficiency and quality at every step.');
content = content.replace(/Get a customised project proposal with capacity recommendations, plant layout, equipment list,[\s\S]*?timeline, and investment estimate — all tailored to your specific requirements\./g, 'Get a customized flour milling solution designed for high productivity, premium flour quality and long-term operational efficiency.');

fs.writeFileSync(filePath, content);
console.log('Update finished.');
