name: Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: false
        default: 'production'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Incremental Deploy (Only Updated Files via LFTP)
        run: |
          lftp -c "
          set ftp:ssl-allow true;
          set ftp:ssl-force true;
          set ssl:verify-certificate false;
          open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' ftps://${{ secrets.FTP_HOST }}:21;
          mirror --reverse --only-newer --parallel=10 --verbose ./dist/ ./;
          "
